cabal-version:       2.2

name:                llamac
version:             0.1.0.0
synopsis:            A compiler for the language llama implemented in Haskell
homepage:            https://github.com/gmagaf/llamac#readme
license:             BSD-3-Clause
license-file:        LICENSE
author:              Gmagaf
maintainer:          example@example.com
copyright:           2025 Gmagaf
category:            Compiler
build-type:          Simple
extra-source-files:  README.md
                     src/Lexer/Lexer.x
                     src/Parser/Parser.y

description:         A compiler for the language llama implemented in Haskell

source-repository head
  type:     git
  location: https://github.com/gmagaf/llamac.git

library
  default-language:   Haskell2010
  hs-source-dirs:     src
  exposed-modules:    Lexer.Lexer
                      Parser.Parser
                      Parser.ParserT
                      Parser.ParserM
                      Parser.ParserState
                      Parser.Utils
                      Common.Token
                      Common.AST
                      Common.PrintAST
                      Common.SymbolType
                      Common.SymbolTable
                      Semantics.SemanticState
                      Semantics.TypeConstraints
                      Semantics.Semantics
                      Semantics.TypeAnalysis
                      Semantics.ExprAnalysis
                      Semantics.Utils
                      Semantics.Unifier
                      RunTime.LibHeaders
                      IR.CodeGenState
                      IR.TypeUtils
  build-depends:      base >= 4.7 && < 5,
                      array >= 0.4 && < 0.6,
                      mtl >= 2.2,
                      transformers >= 0.5,
                      containers >= 0.4,
                      lens >= 5.0,
                      dependent-map >= 0.4,
                      dependent-sum >= 0.7.1,
                      dependent-sum-template >= 0.1,
                      constraints-extras >= 0.3,
                      bytestring >= 0.10 && < 0.11,
                      text >= 1.2 && < 2.0,
                      pretty-simple >= 4.0,
                      llvm-hs-pure   >= 9.0 && < 9.1,
                      llvm-hs-pretty >= 0.9 && < 0.10,
                      prettyprinter >= 1.7
  build-tool-depends: alex:alex >= 3.2,
                      happy:happy >= 1.20
  ghc-options:        -Wall
                      -Wcompat
                      -Widentities
                      -Wincomplete-record-updates
                      -Wincomplete-uni-patterns
                      -Wmissing-export-lists
                      -Wmissing-home-modules
                      -Wpartial-fields
                      -Wredundant-constraints

executable llamac
  default-language:   Haskell2010
  hs-source-dirs:     exe
  main-is:            Main.hs
  build-depends:      base >= 4.7 && < 5,
                      llamac
  other-modules:
  ghc-options:        -Wall
                      -Wcompat
                      -Widentities
                      -Wincomplete-record-updates
                      -Wincomplete-uni-patterns
                      -Wmissing-export-lists
                      -Wmissing-home-modules
                      -Wpartial-fields
                      -Wredundant-constraints

executable repl
  default-language:   Haskell2010
  hs-source-dirs:     repl
  main-is:            Main.hs
  build-depends:      base >= 4.7 && < 5,
                      transformers >= 0.5,
                      mtl >= 2.2,
                      containers >= 0.4,
                      haskeline >= 0.8.1,
                      llamac
  other-modules:      Common.Value
                      Common.RunTimeEnv
                      Common.Interpreter
                      Common.Utils
                      BackEnd.RunTimeLib
                      BackEnd.Evaluation
                      FrontEnd.ReplInput
                      FrontEnd.FrontEnd
  ghc-options:        -Wall
                      -Wcompat
                      -Widentities
                      -Wincomplete-record-updates
                      -Wincomplete-uni-patterns
                      -Wmissing-export-lists
                      -Wmissing-home-modules
                      -Wpartial-fields
                      -Wredundant-constraints

test-suite test
 default-language:    Haskell2010
 hs-source-dirs:      test
 type:                exitcode-stdio-1.0
 main-is:             Tests.hs
 build-depends:       base >= 4.7 && < 5,
                      array >= 0.4 && < 0.6,
                      containers >= 0.4,
                      generic-random >=1.5,
                      QuickCheck >= 2.5,
                      hspec >= 2.8,
                      llamac
 other-modules:       Unit.Unit
                      Unit.Parser.ExpectedASTs
                      Unit.Semantics.SemanticTestSuites
                      Unit.Semantics.AnalyzedASTs
                      Property.Utils
                      Property.Property
                      Property.Lexer.ArbitraryTokens
                      Property.Parser.ArbitraryAST
                      Property.Semantics.SemanticAST
 ghc-options:         -Wall
                      -Wcompat
                      -Widentities
                      -Wincomplete-record-updates
                      -Wincomplete-uni-patterns
                      -Wmissing-export-lists
                      -Wmissing-home-modules
                      -Wpartial-fields
                      -Wredundant-constraints
