module Unit.Semantics.SemanticTestSuites (module Unit.Semantics.SemanticTestSuites) where

typeDefSuite :: [(String, Bool)]
typeDefSuite =
    [
    ("type color = Red | Green | Blue", True),
    ("type t = T", True),
    ("type t = T of unit", True),
    ("type t = T of int", True),
    ("type t = T of char", True),
    ("type t = T of bool", True),
    ("type t = T of float", True),
    ("type t = T of t", True),
    ("type t = T of unit ref", True),
    ("type t = T of int ref", True),
    ("type t = T of char ref", True),
    ("type t = T of bool ref", True),
    ("type t = T of float ref", True),
    ("type t = T of t ref", True),
    ("type t = T of array of unit", True),
    ("type t = T of array [*] of unit", True),
    ("type t = T of array [*, *, *] of unit", True),
    ("type t = T of array of int", True),
    ("type t = T of array [*] of int", True),
    ("type t = T of array [*, *, *] of int", True),
    ("type t = T of array of char", True),
    ("type t = T of array [*] of char", True),
    ("type t = T of array [*, *, *] of char", True),
    ("type t = T of array of bool", True),
    ("type t = T of array [*] of bool", True),
    ("type t = T of array [*, *, *] of bool", True),
    ("type t = T of array of float", True),
    ("type t = T of array [*] of float", True),
    ("type t = T of array [*, *, *] of float", True),
    ("type t = T of array of t", True),
    ("type t = T of array [*] of t", True),
    ("type t = T of array [*, *, *] of t", True),
    ("type t = T of (unit -> unit) -> unit -> unit", True),
    ("type t = T of (int -> int) -> int -> int", True),
    ("type t = T of (char -> char) -> char -> char", True),
    ("type t = T of (bool -> bool) -> bool -> bool", True),
    ("type t = T of (float -> float) -> float -> float", True),
    ("type t = T of (t -> t) -> t -> t", True),
    ("type t = T of int t", True),
    ("type t = T of unit int char float t", True),
    ("type t = T of unit int char float t t -> t array of t t ref", True),
    ("type t = T of int -> char t ref", True),
    ("type t = T_int of int | T_float of array [*, *] of float | T_char of char", True),
    ("type t1 = T1 of t1 t2 and t2 = T2 of t2 t1", True),
    ("type t1 = T1 of t1 array [*, *] of t2 and t2 = T2 of t2 t1 ref", True),
    ("type t1 = T of t1 t2 and t2 = T of t2 t1", True),
    ("type s = K of s -> t -> s and t = L | R", True),
    ("type number = Integer of int | Real of float | Complex of float float", True),
    ("type list = Nil | Cons of int list", True),
    ("type tree = Leaf | Node of int forest and forest = Empty | NonEmpty of tree forest", True),
    ("type t1 = T1 of t2 and t2 = T2 of t3 and t3 = T3 of t4 and t4 = T4 of t5 and t5 = T5 of t1", True),
    ("type t1 = T1 and t1 = T1", True),
    -- Failing cases
    ("type void = ", False),
    ("type t = T1 | T1", False),
    ("type t = R of r", False)
    ]

letDefSuite :: [(String, Bool)]
letDefSuite =
    [
    -- Constants
    ("let x = 3 let y = x + 1", True),
    ("let x : int = 3 let y : int = x + 1", True),
    ("let a = 3 and b = 7 let a = b and b = a ", True),
    ("let x = 3.14", True),
    ("let x = 'a'", True),
    ("let x = '\x42'", True),
    ("let u = ()", True),
    ("let t = true", True),
    ("let f = false", True),
    ("let f = \"test string\"", True),
    -- Typed constants
    ("let x : float = 3.14", True),
    ("let x : char = 'a'", True),
    ("let x : char = '\x42'", True),
    ("let u : unit = ()", True),
    ("let t : bool = true", True),
    ("let f : bool = false", True),
    ("let f : array of char = \"test string\"", True),
    ("let main = 42", True),
    ("let main : int = 42", True),
    ("let s = \"this is a string\" and c : char = 'c'", True),
    -- Mutables
    ("let mutable x : int", True),
    ("let mutable a [5, 3] : float", True),
    ("let mutable x : array of int ref", True),
    ("let mutable a [5, 3] : array of int ref", True),
    ("let mutable f : float and f (x : int) : int = 5\nlet g : int = f 42", True),
    -- Functions
    ("let inc x = x + 1", True),
    ("let odd x = x mod 2 <> 0", True),
    ("let inc (x : int) : int = x + 1", True),
    ("let odd (x : int) : bool = x mod 2 <> 0", True),
    ("let twice f x = f (f x)", True),
    ("let inc x = x + 1\nlet twice f x = f (f x)\nlet y = twice inc 5 ", True),
    ("let f (x : int) : int = x", True),
    ("let f (x : int) (a : char) : int = x", True),
    ("let f (x : int) a = x", True),
    ("let main a b = a b", True),
    ("let main a b = a b and f x = x", True),
    ("let main = 42 and f x = x", True),
    -- Scopes
    ("let f f x = f x and f x = x + 1 let y = f 4", True),
    ("let main = 42 and main : float = 17.0", True),
    ("let ar id (f : int ref) g x (ar : array of float) = let d : int = id 2 in ar", True),
    ("let id id x = let c = id x in x", True),
    ("let main id x = let c = id x in c", True),
    ("let f id b = let c a = id a in c b", True),
    ("let f (x : int) = let x = 'c' in x", True),
    ("type t = T\nlet t : t = T", True),
    ("type t = T\nlet t = T", True),
    ("type t = T of t\nlet t (t : t) = t\nlet g t : t = T t", True),
    -- Polymorphic functions
    ("let id x = x\nlet x : int = id 17 and y : char = id 'a'", True),
    ("let const x : int = 42\nlet x = const 17 and y = const 'a'", True),
    -- Failing cases
    ("let f = g", False),
    ("let f x = g x and g x = x", False),
    ("let f (x : int) (x : int) = 5", False),
    ("let f (x : int) : int = 5 and mutable f : float\nlet g : int = f 42", False),
    ("let f (x : int) : int = 5.0", False),
    ("let f : t = T", False),
    ("let f x = f x", False),
    ("let f (x : int) : int = let x = 'c' in x", False),
    ("let f (x : int) : int = x and c = 'c'\nlet g x = f c", False),
    ("type t = T of t\nlet t (t : t) = t\nlet (g : t) : t = T", False),
    ("type t = R and t = T let t : t = R", False),
    ("type t = R type t = T let t : t = R", False),
    ("type t = R of int and t = T let t : t = R 0", False),
    ("type t = R of int type t = T let t : t = R 0", False),
    ("type t = R of int and s = R of char let t = R 0", False),
    ("type t = R let c = R type t = T let ct : t = c", False),
    ("let rec f = let mutable x in !x let x : int = f and y : char = f", False)
    ]

letRecSuites :: [(String, Bool)]
letRecSuites =
    [
    ("let rec fact n = if n = 0 then 1 else n * fact (n-1)", True),
    ("let rec even n = if n = 0 then true else odd (n-1)\nand odd n = if n = 0 then false else even (n-1)", True),
    ("let rec id x = x and g a = id a + 1\nlet x = id 'a' and y = id 0.42", True),
    ("let rec main = 42", True),
    ("let rec f a = main a and main a = 42 and g a = main a", True),
    ("let rec f x = main x and main a = 42 and g x = main x", True),
    ("let rec f (x : int) : int = main x and main a = 42 and g x = main x", True),
    ("let rec f (i : int) : int = main i and main a = 42 and g x = main x", True),
    ("let rec mutable x and main : int ref = x", True),
    ("let rec main : int ref = x and mutable x", True),
    ("let rec mutable a [3, 4] : int and mutable a [42]", True),
    ("let k (x : int) (y : int) : int = 5 let rec f x = k (g x) x and g y = k y (f y)", True),
    ("let rec f x = x and g = f 4", True),
    ("let rec f x = x and mutable a [f 4, 5] : float", True),
    ("let rec f x = f x", True),
    ("let rec f x = f (g x) and g (x : int) : int = g (f x)", True),
    ("let rec f x = f (g x) and g x = g (f x)", True),
    ("let rec f x y = f y y and mutable ar [f 3 (f 0 42)]", True),
    ("let rec f x = x and mutable ar[f 42]", True),
    ("let id x = x\nlet c = id 3 and d = id 'a'", True),
    ("let rec id x = x and c x = id 1 and main y = id y", True),
    ("let rec id x = x and f : int ref = x and g x = id x and mutable x and mutable ar [id 2] : float", True),
    ("let rec id x = x and f : int ref = x and g x = id x and mutable x and mutable ar [id 2, g 3] : float", True),
    ("let rec mutable x [3] : float and mutable x : char", True),
    ("let rec id id x = let rec c = id x in c", True),
    ("let rec f x = main x and main a = 42 and mutable x and g = x", True),
    ("let rec f x = let mutable x in !x let x : int = f 3 and y = f 'a'", True),
    ("let rec f x = let mutable x in x := 42; !x and x : int = f 3", True),
    ("let rec f x = let mutable x in !x and x : int = f 3", False),
    -- Failing cases
    ("let rec f = main and main a = 42 and g = main and k1 = main 'c' and k2 = main 9.0", False),
    ("let rec f = main and main a = 42 and g (a : int) = main a and k1 = main 'c' and k2 = main 9.0", False),
    ("let rec id x = x and c = id 3 and d = id 'a'", False),
    ("let rec f x = x and g : int -> int = f", False),
    ("let rec f x = x and g = f", False),
    ("let rec f = main and main a = 42 and g = main", False),
    ("let rec f : int -> int = main and main a = 42 and g = main", False),
    ("let rec id x = x and c x = id 1 and main = id", False),
    ("let rec f = main and main a = 42 and mutable x and g = x", False),
    ("let rec f x = let mutable x in !x and x : int = f 3 and y = f 'a'", False)
    ]

exprSuites :: [(String, Bool)]
exprSuites =
    [
        ("let rec mutable a [1, 2, 3] and d1 = dim 1 a and d2 = dim 2 a and d3 = dim 3 a", True),
        ("let main id x = let c1 a = id a in let c2 a = c1 a in c2 x", True),
        ("let rec mutable x and f : int = !x", True),
        ("let rec mutable x : int and f : int = -!x", True),
        ("let f (x : int) : int = +x", True),
        ("let f (x : float) : float = +.x", True),
        ("let f (x : float) : float = -.x", True),
        ("let my_not (x : bool) : bool = not x", True),
        ("let f x = + x", True),
        ("let my_op (x : int) (y : int) : int = x + y", True),
        ("let my_op (x : int) (y : int) : int = x - y", True),
        ("let my_op (x : int) (y : int) : int = x * y", True),
        ("let my_op (x : int) (y : int) : int = x / y", True),
        ("let my_op (x : int) (y : int) : int = x mod y", True),
        ("let my_op (x : float) (y : float) : float = x +. y", True),
        ("let my_op (x : float) (y : float) : float = x -. y", True),
        ("let my_op (x : float) (y : float) : float = x *. y", True),
        ("let my_op (x : float) (y : float) : float = x /. y", True),
        ("let my_op (x : float) (y : float) : float = x ** y", True),
        ("let my_op (x : bool) (y : bool) : bool = x && y", True),
        ("let my_op (x : bool) (y : bool) : bool = x || y", True),
        ("let f (x : char) (y : int) : int = x ; y", True),
        ("let f (x : int) (y : int) : bool = x = y", True),
        ("let f (x : int) (y : int) : bool = x <> y", True),
        ("let f (x : int) (y : int) : bool = x == y", True),
        ("let f (x : int) (y : int) : bool = x != y", True),
        ("type t = T let f (x : t) (y : t) : bool = x = y", True),
        ("type t = T let f (x : t) (y : t) : bool = x <> y", True),
        ("type t = T let f (x : t) (y : t) : bool = x == y", True),
        ("type t = T let f (x : t) (y : t) : bool = x != y", True),
        ("let f (x : int ref) (y : int ref) : bool = x = y", True),
        ("let f (x : int ref) (y : int ref) : bool = x <> y", True),
        ("let f (x : int ref) (y : int ref) : bool = x == y", True),
        ("let f (x : int ref) (y : int ref) : bool = x != y", True),
        ("let f (x : int) (y : int) : bool = x < y", True),
        ("let f (x : int) (y : int) : bool = x > y", True),
        ("let f (x : int) (y : int) : bool = x <= y", True),
        ("let f (x : int) (y : int) : bool = x >= y", True),
        ("let rec mutable x : int and f : unit = x := 4", True),
        ("let rec mutable x and f : unit = x := 4", True),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, 1]", True),
        ("let rec mutable a [0, 1, 3] and f : int = !a[3, 5, 9] + 4", True),
        ("let f (ar : array [*, *, *] of float) = ar[0,0,0]", True),
        ("let f (ar : array [*, *, *] of float) = dim 2 ar", True),
        ("let f : int ref = new int", True),
        ("let f : char ref = new char", True),
        ("let f : float ref = new float", True),
        ("let f : bool ref = new bool", True),
        ("let f : unit ref = new unit", True),
        ("type t = T let f : (int -> int -> t ref -> array of (bool ref)) ref = new int -> int -> t ref -> array of (bool ref)", True),
        ("let rec f = new int and g = delete f", True),
        ("let main = begin 4 end", True),
        ("let f x y z = if x then y else z", True),
        ("let f x y z = if x then y", True),
        ("let main = while true do () done", True),
        ("let rec pr i = () and main = for i = 17 to 42 do pr i done", True),
        ("let rec mutable x : int and main = for i = 17 to 42 do x := i done", True),
        ("let rec pr i = () and main = for i = 42 downto 17 do pr i done", True),
        ("let rec mutable x : int and main = for i = 42 downto 17 do x := i done", True),
        ("let main x = match x with y -> y end", True),
        ("type t = T of t let main x = match x with y -> T y end", True),
        ("let print_int i = ()\n" ++
         "and print_float f = ()\n" ++
         "and print_string s = ()\n" ++
         "and abs_float f = f\n" ++
         "type number = Integer of int | Real of float | Complex of float float\n" ++
         "let main num =\n" ++
         "  match num with\n" ++
         "    Integer i      -> print_int i\n" ++
         "  | Real f         -> print_float f\n" ++
         "  | Complex re 0.0 -> print_float re\n" ++
         "  | Complex 0.0 im -> print_string \"j\"; print_float im\n" ++
         "  | Complex re im  -> print_float re;\n" ++
         "                      print_string (if im > 0.0 then \"+j\" else \"-j\");" ++
         "                      print_float (abs_float im)\n" ++
         "  end", True),
        ("type t = T of bool and s = S of t let main s = match s with S x -> () end", True),
        ("type t = T of bool and s = S of t let main s = match s with S t -> match t with T true -> () end end", True),
        ("type t = T of int let main x = match x with T f -> f = f end", True),
        -- Failing cases
        ("type t = T of t int \nlet t (t : t) = t\nlet g t : t -> t = T t", False),
        ("let rec mutable a [1, 2, 3] and d = dim 0 a", False),
        ("let rec mutable a [1, 2, 3] and d = dim 42 a", False),
        ("let main id x = let c a = id a in c x let f = c 4", False),
        ("let main id x = let c1 a = c2 a in let c2 a = id a in x", False),
        ("let rec mutable x : float and f : int = !x", False),
        ("let rec mutable x : float and f : int = -!x", False),
        ("let f (x : char) = +x", False),
        ("let f (x : char) = +.x", False),
        ("let f (x : char) = -.x", False),
        ("let my_not (x : char) = not x", False),
        ("let my_op (x : char) (y : int) : int = x + y", False),
        ("let my_op (x : int) (y : char) : int = x + y", False),
        ("let my_op (x : int) (y : int) : char = x + y", False),
        ("let my_op (x : char) (y : int) : int = x - y", False),
        ("let my_op (x : char) (y : int) : int = x * y", False),
        ("let my_op (x : char) (y : int) : int = x / y", False),
        ("let my_op (x : char) (y : int) : int = x mod y", False),
        ("let my_op (x : float) (y : char) : float = x +. y", False),
        ("let my_op (x : float) (y : char) : float = x -. y", False),
        ("let my_op (x : float) (y : char) : float = x *. y", False),
        ("let my_op (x : float) (y : char) : float = x /. y", False),
        ("let my_op (x : float) (y : char) : float = x ** y", False),
        ("let my_op (x : bool) (y : bool) : char = x && y", False),
        ("let my_op (x : bool) (y : bool) : char = x || y", False),
        ("let my_op (x : bool) (y : char) : bool = x && y", False),
        ("let my_op (x : bool) (y : char) : bool = x || y", False),
        ("let my_op (x : char) (y : bool) : bool = x && y", False),
        ("let my_op (x : char) (y : bool) : bool = x || y", False),
        ("let f (x : char) (y : char) : int = x ; y", False),
        ("let f x y : int -> int -> char = x = y", False),
        ("let f x y : int -> int -> char = x <> y", False),
        ("let f x y : int -> int -> char = x == y", False),
        ("let f x y : int -> int -> char = x != y", False),
        ("let f x y : int -> int -> char = x < y", False),
        ("let f x y : int -> int -> char = x > y", False),
        ("let f x y : int -> int -> char = x <= y", False),
        ("let f x y : int -> int -> char = x >= y", False),
        ("let f x y : int -> char -> bool = x = y", False),
        ("let f x y : int -> char -> bool = x <> y", False),
        ("let f x y : int -> char -> bool = x == y", False),
        ("let f x y : int -> char -> bool = x != y", False),
        ("let f x y : int -> char -> bool = x < y", False),
        ("let f x y : int -> char -> bool = x > y", False),
        ("let f x y : int -> char -> bool = x <= y", False),
        ("let f x y : int -> char -> bool = x >= y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x = y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x <> y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x == y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x != y", False),
        ("let f x y : array of float -> array of float -> bool = x = y", False),
        ("let f x y : array of float -> array of float -> bool = x <> y", False),
        ("let f x y : array of float -> array of float -> bool = x == y", False),
        ("let f x y : array of float -> array of float -> bool = x != y", False),
        ("let f x y : unit -> unit -> bool = x < y", False),
        ("let f x y : unit -> unit -> bool = x > y", False),
        ("let f x y : unit -> unit -> bool = x <= y", False),
        ("let f x y : unit -> unit -> bool = x >= y", False),
        ("let main f g = let b = f = g in f 4", False),
        ("let main f g = f = g and add x y = x + y let r = main add add", False),
        ("let rec mutable x : int and f : unit = x := 4.9", False),
        ("let rec mutable x and f : bool = x := 4", False),
        ("let rec x = 4 and y = x[4]", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5]", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, 9, 9]", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, '9']", False),
        ("let rec mutable a [0, 1, 3] : int and f : int = a[3, 5, 9]", False),
        ("let rec mutable a [0, 1, 3] : int and f : float ref = a[3, 5, 9]", False),
        ("let f : int = new int", False),
        ("let f : int = new array of int", False),
        ("let rec f = new int and g : bool = delete f", False),
        ("let g : bool = delete 4", False),
        ("let f (x : char) y z = if x then y else z", False),
        ("let f (x : char) y z = if x then y", False),
        ("let f (x : bool) (y : int) (z : float) = if x then y else z", False),
        ("let f (x : bool) (y : int) = if x then y", False),
        ("let f (x : bool) (y : int) (z : int) : bool -> int -> int -> float = if x then y else z", False),
        ("let f (x : bool) (y : unit) = + if x then y", False),
        ("let main = while true do 5 done", False),
        ("let main = while 5 do () done", False),
        ("let main : int = while true do () done", False),
        ("let rec mutable x : char and main = for i = 17 to 42 do x := i done", False),
        ("let main = for i = 17 to 42 do () done let f = i", False),
        ("let main : int = for i = 17 to 42 do () done let f = i", False),
        ("let main : int = for i = 17 to () do () done let f = i", False),
        ("let main : int = for i = () to 42 do () done let f = i", False),
        ("let rec mutable x : char and main = for i = 17 downto 42 do x := i done", False),
        ("let main = for i = 17 downto 42 do () done let f = i", False),
        ("let main : int = for i = 17 downto 42 do () done let f = i", False),
        ("let main : int = for i = 17 downto () do () done let f = i", False),
        ("let main : int = for i = () downto 42 do () done let f = i", False),
        ("let main x = match x with 0 -> () | 1 -> 'f' end", False),
        ("let main x = match x with 0 -> () | 1 -> () end", False),
        ("let main x = match x with y -> y 0 end", False),
        ("let main x = match x with y -> y [0] end", False),
        ("let main x = match x with y -> !y end", False),
        ("let rec main x = match x with y -> y (main y) end", False),
        ("type t = T of bool and s = S of t let main s = match s with S (T true) -> () end", False),
        ("let main x = match x with f -> f end + 3", False)
    ]