module Unit.SemanticTestSuites (module Unit.SemanticTestSuites) where

typeDefSuite :: [(String, Bool)]
typeDefSuite =
    [
    ("type t = T", True),
    ("type t = T of int", True),
    ("type t = T of int t", True),
    ("type t = T of int -> char t ref", True),
    ("type t = T_int of int | T_float of array [*, *] of float | T_char of char", True),
    ("type t1 = T1 of t1 t2 and t2 = T2 of t2 t1", True),
    ("type t1 = T1 of t1 array [*, *] of t2 and t2 = T2 of t2 t1 ref", True),
    ("type t1 = T of t1 t2 and t2 = T of t2 t1", True),
    ("type s = K of s -> t -> s and t = L | R", True),
    -- Failing cases
    ("type t = T1 | T1", False),
    ("type t = R of r", False)
    ]

letDefSuite :: [(String, Bool)]
letDefSuite =
    [
    ("let main = 42", True),
    ("let main : int = 42", True),
    ("let f (x : int) : int -> int = x", True),
    ("let f (x : int) a : int -> char -> int = x", True),
    ("let f (x : int) a = x", True),
    ("let main = 42 and main : float = 17.0", True),
    ("let s = \"this is a string\" and c : char = 'c'", True),
    ("let main = 42 and f x = x", True),
    ("let main a b = a b", True),
    ("let main a b = a b and f x = x", True),
    ("let ar id (f : int ref) g x (ar : array of float) = let d : int = id 2 in ar", True),
    ("type t = T\nlet t : t = T", True),
    ("type t = T\nlet t = T", True),
    ("type t = T of t\nlet t (t : t) = t\nlet g t : t -> t = T t", True),
    ("let id id x = let c = id x in x", True),
    ("let main id x = let c = id x in c", True),
    ("let f id b = let c a = id a in c b", True),
    ("let mutable f : float and f x : int -> int = 5\nlet g : int = f 42", True),
    ("let f (x : int) = let x = 'c' in x", True),
    -- Failing cases
    ("let f = g", False),
    ("let f x = g x and g x = x", False),
    ("let f (x : int) (x : int) = 5", False),
    ("let f x : int -> int = 5 and mutable f : float\nlet g : int = f 42", False),
    ("let f x : int -> int = 5.0", False),
    ("let f : t = T", False),
    ("let f x = f x", False),
    ("let f x : int -> int = let x = 'c' in x", False),
    ("let f x : int -> int = x and c = 'c'\nlet g x = f c", False),
    ("type t = T of t\nlet t (t : t) = t\nlet g : t -> t = T", False)
    ]

letRecSuites :: [(String, Bool)]
letRecSuites =
    [
    ("let rec main = 42", True),
    ("let rec f a = main a and main a = 42 and g a = main a", True),
    ("let rec f x = main x and main a = 42 and g x = main x", True),
    ("let rec f x : int -> int = main x and main a = 42 and g x = main x", True),
    ("let rec f i : int -> int = main i and main a = 42 and g x = main x", True),
    ("let rec mutable x and main : int ref = x", True),
    ("let rec main : int ref = x and mutable x", True),
    ("let rec mutable a [3, 4] : int and mutable a [42]", True),
    ("let k x y : int -> int -> int = 5 let rec f x = k (g x) x and g y = k y (f y)", True),
    ("let rec f x = x and g = f 4", True),
    ("let rec f x = x and mutable a [f 4, 5] : float", True),
    ("let rec f x = f x", True),
    ("let rec f x = f (g x) and g x : int -> int = g (f x)", True),
    ("let rec f x = f (g x) and g x = g (f x)", True),
    ("let rec f x y = f y y and mutable ar [f 3 (f 0 42)]", True),
    ("let rec f x = x and mutable ar[f 42]", True),
    ("let id x = x\nlet c = id 3 and d = id 'a'", True),
    ("let rec id x = x and c x = id 1 and main y = id y", True),
    ("let rec id x = x and f : int ref = x and g x = id x and mutable x and mutable ar [id 2] : float", True),
    ("let rec id x = x and f : int ref = x and g x = id x and mutable x and mutable ar [id 2, g 3] : float", True),
    ("let rec mutable x [3] : float and mutable x : char", True),
    ("let rec id id x = let rec c = id x in c", True),
    ("let rec f x = main x and main a = 42 and mutable x and g = x", True),
    -- Failing cases
    ("let rec f = main and main a = 42 and g = main and k1 = main 'c' and k2 = main 9.0", False),
    ("let rec f = main and main a = 42 and g (a : int) = main a and k1 = main 'c' and k2 = main 9.0", False),
    ("let rec id x = x and c = id 3 and d = id 'a'", False),
    ("let rec f x = x and g : int -> int = f", False),
    ("let rec f x = x and g = f", False),
    ("let rec f = main and main a = 42 and g = main", False),
    ("let rec f : int -> int = main and main a = 42 and g = main", False),
    ("let rec id x = x and c x = id 1 and main = id", False),
    ("let rec f = main and main a = 42 and mutable x and g = x", False)
    ]

exprSuites :: [(String, Bool)]
exprSuites =
    [
        ("let rec mutable a [1, 2, 3] and d1 = dim 1 a and d2 = dim 2 a and d3 = dim 3 a", True),
        ("let main id x = let c1 a = id a in let c2 a = c1 a in c2 x", True),
        ("let rec mutable x and f : int = !x", True),
        ("let rec mutable x : int and f : int = -!x", True),
        ("let f x : int -> int = +x", True),
        ("let f x : float -> float = +.x", True),
        ("let f x : float -> float = -.x", True),
        ("let my_not x : bool -> bool = not x", True),
        ("let f x = + x", True),
        ("let my_op x y : int -> int -> int = x + y", True),
        ("let my_op x y : int -> int -> int = x - y", True),
        ("let my_op x y : int -> int -> int = x * y", True),
        ("let my_op x y : int -> int -> int = x / y", True),
        ("let my_op x y : int -> int -> int = x mod y", True),
        ("let my_op x y : float -> float -> float = x +. y", True),
        ("let my_op x y : float -> float -> float = x -. y", True),
        ("let my_op x y : float -> float -> float = x *. y", True),
        ("let my_op x y : float -> float -> float = x /. y", True),
        ("let my_op x y : float -> float -> float = x ** y", True),
        ("let my_op x y : bool -> bool -> bool = x && y", True),
        ("let my_op x y : bool -> bool -> bool = x || y", True),
        ("let f (x : char) (y : int) : char -> int -> int = x ; y", True),
        ("let f x y : int -> int -> bool = x = y", True),
        ("let f x y : int -> int -> bool = x <> y", True),
        ("let f x y : int -> int -> bool = x == y", True),
        ("let f x y : int -> int -> bool = x != y", True),
        ("type t = T let f x y : t -> t -> bool = x = y", True),
        ("type t = T let f x y : t -> t -> bool = x <> y", True),
        ("type t = T let f x y : t -> t -> bool = x == y", True),
        ("type t = T let f x y : t -> t -> bool = x != y", True),
        ("let f x y : int ref -> int ref -> bool = x = y", True),
        ("let f x y : int ref -> int ref -> bool = x <> y", True),
        ("let f x y : int ref -> int ref -> bool = x == y", True),
        ("let f x y : int ref -> int ref -> bool = x != y", True),
        ("let f x y : int -> int -> bool = x < y", True),
        ("let f x y : int -> int -> bool = x > y", True),
        ("let f x y : int -> int -> bool = x <= y", True),
        ("let f x y : int -> int -> bool = x >= y", True),
        ("let rec mutable x : int and f : unit = x := 4", True),
        ("let rec mutable x and f : unit = x := 4", True),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, 1]", True),
        ("let rec mutable a [0, 1, 3] and f : int = !a[3, 5, 9] + 4", True),
        -- Failing cases
        ("type t = T of t int \nlet t (t : t) = t\nlet g t : t -> t = T t", False),
        ("let rec mutable a [1, 2, 3] and d = dim 0 a", False),
        ("let rec mutable a [1, 2, 3] and d = dim 42 a", False),
        ("let main id x = let c a = id a in c x let f = c 4", False),
        ("let main id x = let c1 a = c2 a in let c2 a = id a in x", False),
        ("let rec mutable x : float and f : int = !x", False),
        ("let rec mutable x : float and f : int = -!x", False),
        ("let f (x : char) = +x", False),
        ("let f (x : char) = +.x", False),
        ("let f (x : char) = -.x", False),
        ("let my_not (x : char) = not x", False),
        ("let my_op x y : char -> int -> int = x + y", False),
        ("let my_op x y : int -> char -> int = x + y", False),
        ("let my_op x y : int -> int -> char = x + y", False),
        ("let my_op x y : char -> int -> int = x - y", False),
        ("let my_op x y : char -> int -> int = x * y", False),
        ("let my_op x y : char -> int -> int = x / y", False),
        ("let my_op x y : char -> int -> int = x mod y", False),
        ("let my_op x y : float -> char -> float = x +. y", False),
        ("let my_op x y : float -> char -> float = x -. y", False),
        ("let my_op x y : float -> char -> float = x *. y", False),
        ("let my_op x y : float -> char -> float = x /. y", False),
        ("let my_op x y : float -> char -> float = x ** y", False),
        ("let my_op x y : bool -> bool -> char = x && y", False),
        ("let my_op x y : bool -> bool -> char = x || y", False),
        ("let my_op x y : bool -> char -> bool = x && y", False),
        ("let my_op x y : bool -> char -> bool = x || y", False),
        ("let my_op x y : char -> bool -> bool = x && y", False),
        ("let my_op x y : char -> bool -> bool = x || y", False),
        ("let f (x : char) (y : char) : char -> int -> int = x ; y", False),
        ("let f x y : int -> int -> char = x = y", False),
        ("let f x y : int -> int -> char = x <> y", False),
        ("let f x y : int -> int -> char = x == y", False),
        ("let f x y : int -> int -> char = x != y", False),
        ("let f x y : int -> int -> char = x < y", False),
        ("let f x y : int -> int -> char = x > y", False),
        ("let f x y : int -> int -> char = x <= y", False),
        ("let f x y : int -> int -> char = x >= y", False),
        ("let f x y : int -> char -> bool = x = y", False),
        ("let f x y : int -> char -> bool = x <> y", False),
        ("let f x y : int -> char -> bool = x == y", False),
        ("let f x y : int -> char -> bool = x != y", False),
        ("let f x y : int -> char -> bool = x < y", False),
        ("let f x y : int -> char -> bool = x > y", False),
        ("let f x y : int -> char -> bool = x <= y", False),
        ("let f x y : int -> char -> bool = x >= y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x = y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x <> y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x == y", False),
        ("let f x y : (int -> char) -> (int -> char) -> bool = x != y", False),
        ("let f x y : array of float -> array of float -> bool = x = y", False),
        ("let f x y : array of float -> array of float -> bool = x <> y", False),
        ("let f x y : array of float -> array of float -> bool = x == y", False),
        ("let f x y : array of float -> array of float -> bool = x != y", False),
        ("let f x y : unit -> unit -> bool = x < y", False),
        ("let f x y : unit -> unit -> bool = x > y", False),
        ("let f x y : unit -> unit -> bool = x <= y", False),
        ("let f x y : unit -> unit -> bool = x >= y", False),
        ("let rec mutable x : int and f : unit = x := 4.9", False),
        ("let rec mutable x and f : bool = x := 4", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5]", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, 9, 9]", False),
        ("let rec mutable a [0, 1, 3] and f = a[3, 5, '9']", False),
        ("let rec mutable a [0, 1, 3] : int and f : int = a[3, 5, 9]", False),
        ("let rec mutable a [0, 1, 3] : int and f : float ref = a[3, 5, 9]", False)
    ]